// +build ignore

package main

import (
	"fmt"
	"os"

	"github.com/oreparaz/xsig/internal/crypto"
	ll "github.com/oreparaz/xsig/internal/lowlevel"
	machines "github.com/oreparaz/xsig/internal/machine"
)

func cArray(name string, data []byte) string {
	s := fmt.Sprintf("static const uint8_t %s[] = {", name)
	for i, b := range data {
		if i > 0 {
			s += ","
		}
		if i%16 == 0 {
			s += "\n    "
		}
		s += fmt.Sprintf("0x%02x", b)
	}
	s += "\n};\n"
	return s
}

func main() {
	f, err := os.Create("c/test_vectors.h")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Auto-generated by gen_test_vectors.go — do not edit")
	fmt.Fprintln(f, "#pragma once")
	fmt.Fprintln(f, "#include <stdint.h>")
	fmt.Fprintln(f, "")

	// ===== Test 1: Single signature verification (should pass) =====
	msg1 := []byte("yolo")
	_, pk1, sig1 := crypto.HelperVerifyData(msg1)

	a1 := machines.MachineCode{}
	a1.Append(ll.Push(sig1))
	xsig1 := a1.Serialize(machines.CodeTypeXSig)

	b1 := machines.MachineCode{}
	b1.Append(ll.Push(pk1))
	b1.Append(ll.SignatureVerify())
	xpubkey1 := b1.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 1: Single sig verify (expect pass)")
	fmt.Fprintln(f, cArray("tv1_msg", msg1))
	fmt.Fprintln(f, cArray("tv1_xsig", xsig1))
	fmt.Fprintln(f, cArray("tv1_xpubkey", xpubkey1))
	fmt.Fprintln(f, "static const int tv1_expected = 1;")
	fmt.Fprintln(f, "")

	// ===== Test 2: Single sig, wrong message (should fail) =====
	msg2correct := []byte("correct")
	_, pk2, sig2 := crypto.HelperVerifyData(msg2correct)

	a2 := machines.MachineCode{}
	a2.Append(ll.Push(sig2))
	xsig2 := a2.Serialize(machines.CodeTypeXSig)

	b2 := machines.MachineCode{}
	b2.Append(ll.Push(pk2))
	b2.Append(ll.SignatureVerify())
	xpubkey2 := b2.Serialize(machines.CodeTypeXPublicKey)

	msg2wrong := []byte("wrong")

	fmt.Fprintln(f, "// Test 2: Single sig, wrong message (expect fail)")
	fmt.Fprintln(f, cArray("tv2_msg", msg2wrong))
	fmt.Fprintln(f, cArray("tv2_xsig", xsig2))
	fmt.Fprintln(f, cArray("tv2_xpubkey", xpubkey2))
	fmt.Fprintln(f, "static const int tv2_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 3: 2-of-3 multisig (should pass) =====
	msg3 := []byte("yolo")
	_, pk3a, sig3a := crypto.HelperVerifyData(msg3)
	_, pk3b, sig3b := crypto.HelperVerifyData(msg3)
	_, pk3c, _ := crypto.HelperVerifyData(msg3)

	a3 := machines.MachineCode{}
	a3.Append(ll.Push(sig3a))
	a3.Append(ll.Push(sig3b))
	xsig3 := a3.Serialize(machines.CodeTypeXSig)

	b3 := machines.MachineCode{}
	b3.Append(ll.Push(pk3a))
	b3.Append(ll.Push(pk3b))
	b3.Append(ll.Push(pk3c))
	b3.Append(ll.Push1(2))
	b3.Append(ll.Push1(3))
	b3.Append(ll.MultisigVerify())
	xpubkey3 := b3.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 3: 2-of-3 multisig (expect pass)")
	fmt.Fprintln(f, cArray("tv3_msg", msg3))
	fmt.Fprintln(f, cArray("tv3_xsig", xsig3))
	fmt.Fprintln(f, cArray("tv3_xpubkey", xpubkey3))
	fmt.Fprintln(f, "static const int tv3_expected = 1;")
	fmt.Fprintln(f, "")

	// ===== Test 4: 2-of-3 multisig, wrong message (should fail) =====
	msg4 := []byte("correct")
	_, pk4a, sig4a := crypto.HelperVerifyData(msg4)
	_, pk4b, sig4b := crypto.HelperVerifyData(msg4)
	_, pk4c, _ := crypto.HelperVerifyData(msg4)

	a4 := machines.MachineCode{}
	a4.Append(ll.Push(sig4a))
	a4.Append(ll.Push(sig4b))
	xsig4 := a4.Serialize(machines.CodeTypeXSig)

	b4 := machines.MachineCode{}
	b4.Append(ll.Push(pk4a))
	b4.Append(ll.Push(pk4b))
	b4.Append(ll.Push(pk4c))
	b4.Append(ll.Push1(2))
	b4.Append(ll.Push1(3))
	b4.Append(ll.MultisigVerify())
	xpubkey4 := b4.Serialize(machines.CodeTypeXPublicKey)

	msg4wrong := []byte("wrong")

	fmt.Fprintln(f, "// Test 4: 2-of-3 multisig, wrong message (expect fail)")
	fmt.Fprintln(f, cArray("tv4_msg", msg4wrong))
	fmt.Fprintln(f, cArray("tv4_xsig", xsig4))
	fmt.Fprintln(f, cArray("tv4_xpubkey", xpubkey4))
	fmt.Fprintln(f, "static const int tv4_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 5: 1-of-1 multisig (should pass) =====
	msg5 := []byte("test")
	_, pk5, sig5 := crypto.HelperVerifyData(msg5)

	a5 := machines.MachineCode{}
	a5.Append(ll.Push(sig5))
	xsig5 := a5.Serialize(machines.CodeTypeXSig)

	b5 := machines.MachineCode{}
	b5.Append(ll.Push(pk5))
	b5.Append(ll.Push1(1))
	b5.Append(ll.Push1(1))
	b5.Append(ll.MultisigVerify())
	xpubkey5 := b5.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 5: 1-of-1 multisig (expect pass)")
	fmt.Fprintln(f, cArray("tv5_msg", msg5))
	fmt.Fprintln(f, cArray("tv5_xsig", xsig5))
	fmt.Fprintln(f, cArray("tv5_xpubkey", xpubkey5))
	fmt.Fprintln(f, "static const int tv5_expected = 1;")
	fmt.Fprintln(f, "")

	// ===== Test 6: 3-of-3 multisig (should pass) =====
	msg6 := []byte("test")
	_, pk6a, sig6a := crypto.HelperVerifyData(msg6)
	_, pk6b, sig6b := crypto.HelperVerifyData(msg6)
	_, pk6c, sig6c := crypto.HelperVerifyData(msg6)

	a6 := machines.MachineCode{}
	a6.Append(ll.Push(sig6a))
	a6.Append(ll.Push(sig6b))
	a6.Append(ll.Push(sig6c))
	xsig6 := a6.Serialize(machines.CodeTypeXSig)

	b6 := machines.MachineCode{}
	b6.Append(ll.Push(pk6a))
	b6.Append(ll.Push(pk6b))
	b6.Append(ll.Push(pk6c))
	b6.Append(ll.Push1(3))
	b6.Append(ll.Push1(3))
	b6.Append(ll.MultisigVerify())
	xpubkey6 := b6.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 6: 3-of-3 multisig (expect pass)")
	fmt.Fprintln(f, cArray("tv6_msg", msg6))
	fmt.Fprintln(f, cArray("tv6_xsig", xsig6))
	fmt.Fprintln(f, cArray("tv6_xpubkey", xpubkey6))
	fmt.Fprintln(f, "static const int tv6_expected = 1;")
	fmt.Fprintln(f, "")

	// ===== Test 7: Duplicate sigs rejected in 2-of-3 (should fail) =====
	msg7 := []byte("test")
	_, pk7a, sig7a := crypto.HelperVerifyData(msg7)
	_, pk7b, _ := crypto.HelperVerifyData(msg7)
	_, pk7c, _ := crypto.HelperVerifyData(msg7)

	a7 := machines.MachineCode{}
	a7.Append(ll.Push(sig7a))
	a7.Append(ll.Push(sig7a)) // duplicate!
	xsig7 := a7.Serialize(machines.CodeTypeXSig)

	b7 := machines.MachineCode{}
	b7.Append(ll.Push(pk7a))
	b7.Append(ll.Push(pk7b))
	b7.Append(ll.Push(pk7c))
	b7.Append(ll.Push1(2))
	b7.Append(ll.Push1(3))
	b7.Append(ll.MultisigVerify())
	xpubkey7 := b7.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 7: Duplicate sigs rejected (expect fail)")
	fmt.Fprintln(f, cArray("tv7_msg", msg7))
	fmt.Fprintln(f, cArray("tv7_xsig", xsig7))
	fmt.Fprintln(f, cArray("tv7_xpubkey", xpubkey7))
	fmt.Fprintln(f, "static const int tv7_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 8: Empty input (should fail) =====
	fmt.Fprintln(f, "// Test 8: Empty input (expect fail)")
	fmt.Fprintln(f, "static const uint8_t tv8_msg[] = {0x6d}; // 'm'")
	fmt.Fprintln(f, "static const uint8_t tv8_xsig[] = {0};")
	fmt.Fprintln(f, "static const size_t tv8_xsig_len = 0;")
	fmt.Fprintln(f, "static const uint8_t tv8_xpubkey[] = {0};")
	fmt.Fprintln(f, "static const size_t tv8_xpubkey_len = 0;")
	fmt.Fprintln(f, "static const int tv8_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 9: Garbage prefix (should fail) =====
	fmt.Fprintln(f, "// Test 9: Garbage prefix (expect fail)")
	fmt.Fprintln(f, cArray("tv9_msg", []byte("msg")))
	fmt.Fprintln(f, cArray("tv9_xsig", []byte("garbage")))
	fmt.Fprintln(f, cArray("tv9_xpubkey", []byte("garbage")))
	fmt.Fprintln(f, "static const int tv9_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 10: Valid xsig, xpubkey has unknown opcode (should fail) =====
	a10 := machines.MachineCode{}
	a10.Append(ll.Push1(1))
	xsig10 := a10.Serialize(machines.CodeTypeXSig)

	mc10 := machines.MachineCode{}
	mc10.Code = []byte{0xFF} // unknown opcode
	xpubkey10 := mc10.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 10: xpubkey eval error (expect fail)")
	fmt.Fprintln(f, cArray("tv10_msg", []byte("msg")))
	fmt.Fprintln(f, cArray("tv10_xsig", xsig10))
	fmt.Fprintln(f, cArray("tv10_xpubkey", xpubkey10))
	fmt.Fprintln(f, "static const int tv10_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 11: xsig has unknown opcode (should fail) =====
	mc11 := machines.MachineCode{}
	mc11.Code = []byte{0xFF}
	xsig11 := mc11.Serialize(machines.CodeTypeXSig)

	b11 := machines.MachineCode{}
	b11.Append(ll.Push1(1))
	xpubkey11 := b11.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 11: xsig eval error (expect fail)")
	fmt.Fprintln(f, cArray("tv11_msg", []byte("msg")))
	fmt.Fprintln(f, cArray("tv11_xsig", xsig11))
	fmt.Fprintln(f, cArray("tv11_xpubkey", xpubkey11))
	fmt.Fprintln(f, "static const int tv11_expected = 0;")
	fmt.Fprintln(f, "")

	// ===== Test 12: 3-of-3 with only 2 distinct signers (repeated sig, should fail) =====
	msg12 := []byte("test")
	_, pk12a, sig12a := crypto.HelperVerifyData(msg12)
	_, pk12b, sig12b := crypto.HelperVerifyData(msg12)
	_, pk12c, _ := crypto.HelperVerifyData(msg12)

	a12 := machines.MachineCode{}
	a12.Append(ll.Push(sig12a))
	a12.Append(ll.Push(sig12b))
	a12.Append(ll.Push(sig12a)) // repeated sig1
	xsig12 := a12.Serialize(machines.CodeTypeXSig)

	b12 := machines.MachineCode{}
	b12.Append(ll.Push(pk12a))
	b12.Append(ll.Push(pk12b))
	b12.Append(ll.Push(pk12c))
	b12.Append(ll.Push1(3))
	b12.Append(ll.Push1(3))
	b12.Append(ll.MultisigVerify())
	xpubkey12 := b12.Serialize(machines.CodeTypeXPublicKey)

	fmt.Fprintln(f, "// Test 12: 3-of-3 with only 2 distinct signers (expect fail)")
	fmt.Fprintln(f, cArray("tv12_msg", msg12))
	fmt.Fprintln(f, cArray("tv12_xsig", xsig12))
	fmt.Fprintln(f, cArray("tv12_xpubkey", xpubkey12))
	fmt.Fprintln(f, "static const int tv12_expected = 0;")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "#define NUM_TEST_VECTORS 12")
}
